/**
 * Canonical route inventory for governance tests.
 * Excludes redirects/aliases (e.g. /access-capital, /pre-qualify, /readiness).
 */
export const CANONICAL_ROUTES = [
  "/",
  "/management",
  "/management/formation",
  "/management/business-profile",
  "/management/business-builder",
  "/management/hosting",
  "/management/crm-growth",
  "/consulting",
  "/consulting/coaching",
  "/consulting/structuring",
  "/consulting/capital-strategy",
  "/consulting/product-development",
  "/consulting/book",
  "/consulting/lifecycle/sharpen-your-business-model",
  "/consulting/lifecycle/build-a-predictable-pipeline",
  "/consulting/lifecycle/systemize-your-operations",
  "/consulting/lifecycle/install-your-growth-engine",
  "/consulting/lifecycle/build-the-right-foundation",
  "/consulting/lifecycle/deploy-capital-strategically",
  "/capital",
  "/capital/leverage",
  "/funding",
  "/apply",
  "/funding-readiness",
  "/funding-readiness/individual",
  "/funding-readiness/enroll",
  "/funding-readiness/enroll/three-step",
  "/funding-readiness/enroll/three-step/return",
  "/funding-readiness-survey",
  "/insights",
  "/partners",
  "/about",
  "/contact",
  "/admin",
  "/partner/register",
  "/partner",
  "/referral",
  "/testimonial",
  "/legal/privacy",
  "/legal/terms",
  "/legal/disclosures",
] as const;

export type CanonicalRoute = (typeof CANONICAL_ROUTES)[number];
